Fix build with Qt6
sailfishos/qt-mobility-haptics-ffmemless pull request #1
Opened 2023-08-28 17:00 UTC by jmlich

2023-08-28 18:02 UTC, Thaodan requested changes
Please make the commits match these docs:
https://docs.sailfishos.org/Tools/Sailfish_SDK/Building_packages/#changelog-generation

You can use the bug tag JB#61015.

Also this is about supporting Qt 6 rather than fixing it.

2023-08-31 09:32 UTC, rainemak commented
> Please make the commits match these docs: https://docs.sailfishos.org/Tools/Sailfish_SDK/Building_packages/#changelog-generation
> 
> You can use the bug tag JB#61015.
> 
> Also this is about supporting Qt 6 rather than fixing it.

Guiding to use internal bug references is not really good idea as those are only visible for the internals. Just having "Fix build with Qt6" is perfectly fine. Current commit message is missing period after summary right before JB#61015 and it's missing component name as well. Due missing component name change log would not be generated.  Simpler just to drop JB#61015. 

The one who merges and tags should annotate a tag with correct change log syntax.

My apologies @jmlich that this goes back and forth.

2023-08-31 12:12 UTC, rainemak approved these changes

2023-11-27 13:56 UTC, pvuorela approved these changes
Looks all nice an simple here.

2023-11-27 13:56 UTC, merged